[package]
name = "starlite"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.6"
uefi = { version = "0.33.0", features = ["alloc"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false