[build]
target = "x86_64-unknown-uefi"

[alias]
build-x86_64 = "build --target x86_64-unknown-uefi"
build-aarch64 = "build --target aarch64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "just run-test x86_64"

[target.aarch64-unknown-uefi]
runner = "just run-test aarch64"

[target.i686-unknown-uefi]
runner = "just run-test i686"