[build]
target = "x86_64-unknown-uefi"

[alias]
build-x86_64 = "build --target x86_64-unknown-uefi"
build-aarch64 = "build --target aarch64-unknown-uefi"
build-i686 = "build --target i686-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "just run-test"